# Generated by Django 3.2.2 on 2021-06-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pantallas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ensayos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('grupo', models.CharField(max_length=10)),
                ('num_ensayo', models.IntegerField()),
                ('tipo_ensayo', models.CharField(max_length=10)),
                ('subtipo_ensayo', models.CharField(max_length=10)),
                ('t_acumulado_RC', models.DecimalField(decimal_places=2, max_digits=5)),
                ('t_RC', models.DecimalField(decimal_places=2, max_digits=5)),
                ('t_acumulado_PR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('t_PR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correcta', models.IntegerField()),
                ('intentos', models.IntegerField()),
            ],
        ),
    ]
