# Generated by Django 3.2.2 on 2021-06-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pantallas', '0004_auto_20210619_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='mannekentest',
            name='clave',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
